# Site settings
title: David Martínez Rodríguez
description: > # this means to ignore newlines until "baseurl:"
  Informatics engineer with a scientific heart. Triathlete, cyclist,
  mountaineering lover. This is my blog, my site, a place to store some
  thoughts and share some experiences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davidmr.es" # the base hostname & protocol for your site
twitter_username: nihilsinecaos
github_username: necavit

# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections:
  - thoughts
sass:
  sass_dir: _sass
  style: compressed

# Handling Reading
safe:         false
include:      []
exclude:      []
keep_files:   []
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    redcarpet
highlighter: ""
lsi:         false
excerpt_separator: "\n\n"

# Serving
#    (only in development mode!
#       Nginx will serve content in production)
detach:  false    # detaches the server from the terminal
port:    4000     # TCP port
host:    0.0.0.0  # host name (localhost)

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     /:title # Old: date
paginate_path: /page:num
timezone:      null

quiet:    false
defaults:
  -
    scope:
      path: "_posts"
      type: ""
    values:
      layout: "post"

# Markdown Processors
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:           true
  footnote_nr:        1
  entity_output:      as_char
  toc_levels:         1..6
  smart_quotes:       lsquo,rsquo,ldquo,rdquo
  use_coderay:        false
  input:              GFM
  fenced_code_blocks: true

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

redcloth:
  hard_breaks: true
